function OAS_RICH(position) {
if (position == 'Bottom') {
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('		\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('<script type="text/javascript">\n');
document.write ('//<![CDATA[\n');
document.write ('var filePath                     = "http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-GA-gigasciencejournal-LB/GigaScience_PosLau_Leaderboard_v1.swf/1343036297";\n');
document.write ('var TFSMFlash_PRETAG             = "";\n');
document.write ('var TFSMFlash_POSTTAG            = "";\n');
document.write ('var TFSMFlash_VERSION            = "8";\n');
document.write ('var TFSMFlash_WMODE              = "window";\n');
document.write ('\n');
document.write ('			var TFSMFlash_OASCLICK           = "http://oas.biomedcentral.com/5c/biomedcentral.com/bmcbioinformatics/article/10.1186/1471/2105/13/206/L43/787903637/Bottom/biomed/House-GA-gigasciencejournal-LB/House-GA-gigasciencejournal-LB.html/32506d4b446b764f387a6341446f3736";\n');
document.write ('	\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE   = "?clickTAG="+TFSMFlash_OASCLICK + "";\n');
document.write ('var TFSMFlash_SWFFILE            = filePath + TFSMFlash_SWFCLICKVARIABLE;\n');
document.write ('var TFSMFlash_FSCOMMAND          = "";\n');
document.write ('var TFSMFlash_IMAGEALTERNATE     = "http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-GA-gigasciencejournal-LB/GigaScience_PosLau_Leaderboard_v1.gif/1343036297";\n');
document.write ('\n');
document.write ('\n');
document.write ('var TFSMFlash_OASALTTEXT         = "";\n');
document.write ('var TFSMFlash_OASTARGET          = "_blank";\n');
document.write ('var TFSMFlash_OASPROTOCOL        = "http://";\n');
document.write ('var TFSMFlash_OASDIM             = "width=');
document.write ("'");
document.write ('728px');
document.write ("'");
document.write (' height=');
document.write ("'");
document.write ('90px');
document.write ("'");
document.write ('";\n');
document.write ('var TFSMFlash_OASADID            = "OAS_RMF_Bottom_FLASH";\n');
document.write ('document.write("<"+"scr"+"ipt type=\\');
document.write ('"text/javascript\\');
document.write ('" src=\\');
document.write ('"http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-GA-gigasciencejournal-LB/TFSMFlashWrapper301.js/1343036297\\');
document.write ('"><\\');
document.write ('/scr"+"ipt"+">");\n');
document.write ('//]]>\n');
document.write ('</script>\n');
document.write ('<noscript>\n');
document.write ('	<a href="http://oas.biomedcentral.com/5c/biomedcentral.com/bmcbioinformatics/article/10.1186/1471/2105/13/206/L43/787903637/Bottom/biomed/House-GA-gigasciencejournal-LB/House-GA-gigasciencejournal-LB.html/32506d4b446b764f387a6341446f3736" target="_blank">\n');
document.write ('		<img src="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-GA-gigasciencejournal-LB/GigaScience_PosLau_Leaderboard_v1.gif/1343036297" width="728" height="90" alt="" style="border:0px black solid;" />\n');
document.write ('	</a>\n');
document.write ('</noscript>\n');
document.write ('\n');
document.write ('\n');
}
if (position == 'Top') {
document.write ('\n');
document.write ('<SCRIPT type="text/javascript"> \n');
document.write ('var TFSMFlash_PRETAG="";\n');
document.write ('var TFSMFlash_POSTTAG=""; \n');
document.write ('var TFSMFlash_VERSION="8"; \n');
document.write ('var TFSMFlash_WMODE="window"; \n');
document.write ('var TFSMFlash_OASCLICK="http://oas.biomedcentral.com/5c/biomedcentral.com/bmcbioinformatics/article/10.1186/1471/2105/13/206/L43/1238072094/Top/biomed/House-SE-biodatamining-LB/House-SE-biodatamining-LB.html/32506d4b446b764f387a6341446f3736";\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE="?clickTAG="+TFSMFlash_OASCLICK ; \n');
document.write ('var TFSMFlash_SWFFILE="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SE-biodatamining-LB/BioData_Mining_Leaderboard_v2.swf/1272555148"+TFSMFlash_SWFCLICKVARIABLE; \n');
document.write ('var TFSMFlash_FSCOMMAND=""; \n');
document.write ('var TFSMFlash_IMAGEALTERNATE="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SE-biodatamining-LB/BioData_Mining_Leaderboard_v2.gif/1272555148"; \n');
document.write ('var TFSMFlash_OASALTTEXT=""; \n');
document.write ('var TFSMFlash_OASTARGET="_blank"; \n');
document.write ('var TFSMFlash_OASPROTOCOL="http://"; \n');
document.write ('var TFSMFlash_OASDIM="WIDTH=');
document.write ("'");
document.write ('728');
document.write ("'");
document.write (' HEIGHT=');
document.write ("'");
document.write ('90');
document.write ("'");
document.write ('"; \n');
document.write ('var TFSMFlash_OASADID="OAS_RMF_Top_FLASH"; \n');
document.write ('document.write(');
document.write ("'");
document.write ('<scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt src="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SE-biodatamining-LB/TFSMFlashWrapper204.js/1272555148"></scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt>');
document.write ("'");
document.write ('); \n');
document.write ('</SCRIPT>\n');
document.write ('\n');
document.write ('<NOSCRIPT>\n');
document.write ('<A HREF="http://oas.biomedcentral.com/5c/biomedcentral.com/bmcbioinformatics/article/10.1186/1471/2105/13/206/L43/1238072094/Top/biomed/House-SE-biodatamining-LB/House-SE-biodatamining-LB.html/32506d4b446b764f387a6341446f3736" TARGET="_blank"><IMG SRC="http://imageceu1.247realmedia.com/RealMedia/ads/Creatives/biomed/House-SE-biodatamining-LB/BioData_Mining_Leaderboard_v2.gif/1272555148" WIDTH=');
document.write ("'");
document.write ('728');
document.write ("'");
document.write (' HEIGHT=');
document.write ("'");
document.write ('90');
document.write ("'");
document.write (' BORDER=0 ALT=""></a>\n');
document.write ('</NOSCRIPT>\n');
document.write ('\n');
}
if (position == 'x96') {
document.write ('<A HREF="http://oas.biomedcentral.com/5c/biomedcentral.com/bmcbioinformatics/article/10.1186/1471/2105/13/206/2017448120/x96/default/empty.gif/32506d4b446b764f387a6341446f3736?x" target="_top"><IMG SRC="http://imageceu1.247realmedia.com/0/default/empty.gif"  WIDTH=1 HEIGHT=1 ALT="" BORDER=0 BORDER="0"></A>');
}
}
